### ISSUE TITLE
Error With Lowercase Condition/Sub-Condition

### ISSUE THREAD

**Issue by beaverbrick** [ZZJHONS/Bricksync#6]
Bricksync throws a JSON Parse Error when there is a lowercase condition/sub-condition used in BL's inventory.

I think an expansion of the IF statements in bricklink.c file (at lines 1479 & 1495) to also check for lowercase values should fix it.

![Condition](https://user-images.githubusercontent.com/81053064/111887989-96bb6b00-89d0-11eb-8033-9b7b8d3766ab.png)

![Completeness](https://user-images.githubusercontent.com/81053064/111887897-01b87200-89d0-11eb-9da1-1f2f2d25c077.png)

**Comment by ZZJHONS** [comment]
The problem with lowercase is from Bricklink their system is built to only use uppercase, and wherever the user inputs lowercase Bricklink automatically change it.

But I think the bug was introduced with the new inventory page. Please open a ticket report to them, as if you encounter this error with bricksync you can fix it by updating your inventory on BrickLink and doing blmaster.

**Comment by ZZJHONS** [comment]
Seems Bricklink fixed something related to this:

Fixed capitalization of conditions on items for sale

2022-03-15 - https://www.bricklink.com/help.asp?helpID=2453
